services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "redacted"
    volumes:
      - sql-server-volume:/var/opt/mssql/data

volumes:
  sql-server-volume: